use_frameworks!

target 'BONavigationPullToRefresh_Example' do
  pod 'BONavigationPullToRefresh', :path => '../'

  target 'BONavigationPullToRefresh_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
